name: Search telegram for new channels

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Validate data
      run: python main.py validate
    - name: Search telegram
      run: python main.py search_handles
    - name: Save cache
      uses: EndBug/add-and-commit@v7
      with:
        add: "cache/telegram_search_cache.json"
        message: "Updating search cache"
