name: Update cache and publish site

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency: telegram_checks
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Validate data
      run: python main.py validate
    - name: Update cache
      run: python main.py update_cache
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
    - name: Save cache
      uses: EndBug/add-and-commit@v7
      with:
        add: "cache/channel_cache.json"
        message: "Updating channel cache"
    - name: Create index.html
      run: python main.py create_html
    - uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: public
